services:
  react-ui:
    image: react-ui
    build:
      context: ../src/ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_HOST=http://localhost:8080
    ports:
      - 8081:8080
    container_name: react-ui
    restart: unless-stopped
    networks:
      - app-network
  node-api:
    image: node-api
    build:
      context: ../src/api
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    container_name: node-api
    restart: unless-stopped
    networks:
      - app-network
  nginx-server:
    image: nginx-load-balancer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    container_name: nginx-load-balancer
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
